version: '3.3'
services:
  choregraphe:
    build: .
    image: fero/choregraphe:2.1.4
    volumes:
      - .:/home/naouser/
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY
  choregraphe-i386:
    build: .
    image: fero/choregraphe-i386:2.1.4
    volumes:
      - .:/home/naouser/
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY
